### ISSUE TITLE
dueInSeconds in live update data negative for buses after midnight 

### ISSUE THREAD

**Issue by seanblanchfield** [seanrees/gtfs-upcoming#5]
I'm afraid I introduced this one in PR #4, or at least contributed to it.  In `GetLive()`, when live data for buses after midnight is retrieved, `dueInSeconds` can go negative. This happens because the time in the format "HH:MM:SS" has already been corrected from "24:hh:mm" to "00:hh:mm", and thus an earlier time gets subtracted from the current time by `deltaSeconds()`, which is reached via `parseTime()` and `FromTrip()`.

My instinct here is that the root cause is the passing of times around in the "HH:MM:SS" format, which loses the date information. This might be resolvable by passing an additional "`is_due_tomorrow`" flag through the call chain `GetLive()` -> `FromTrip()` -> `parseTime()`. I feel the better solution is to convert to a `DateTime` as soon as the live data is received, pass the datetimes around instead of the "HH:MM:SS" strings, and then convert to back to a suitable string representation ("HH:MM:SS" or full ISO date) before returning the response to the client.  

I'm willing to fix this on the *you break it you buy it* principle. Before I do, which approach do you think is best?

**Comment by seanrees** [comment]
Ouch. Good catch.

I agree; passing around a `datetime` seems the cleanest. I recall only passing around `HH:MM:SS` because that's the form the schedule takes (for predictable reasons :-)). However, we need to intersect it with the present moment at some point, so pulling that point earlier in processing seems much better than adding a new context flag we'd need to pass around.
